// Code generated by foptgen; DO NOT EDIT.

package hcj

type ParseNodeOption func(ParseNodeOptions) ParseNodeOptions

func WithCSS(v CSS) ParseNodeOption {
	return func(s ParseNodeOptions) ParseNodeOptions {
		s.CSS = v
		return s
	}
}

func WithParentStyle(v map[string]string) ParseNodeOption {
	return func(s ParseNodeOptions) ParseNodeOptions {
		s.ParentStyle = v
		return s
	}
}

func WithInteractiveState(v InteractiveState) ParseNodeOption {
	return func(s ParseNodeOptions) ParseNodeOptions {
		s.InteractiveState = v
		return s
	}
}
